### PR TITLE
Continue to build out SRP functionality

### PR DESCRIPTION
**Pull request by nand-nor**
## Description

This is another PR to continue building out SRP functionality. Adds the following:
- Pins to current `esp-hal` version at git commit `c0a9934`. This is just to help with stability a bit & make sure things still build even if the `esp-hal` adds a new release. Im open to pinning to a different commit if preferred, this one was just the most recent at the time. Also open to handling this differently if there is a cleaner option or some other method preferred. 
- Adds impls for `otPlatRadioGetIeeeEui64`, `otPlatRadioGetRssi`, and `otPlatRadioGetReceiveSensitivity`. 
- Adds some additional methods to help with SRP functionality, mainly extending the SRP API to allow lib users to unregister from the SRP server. Also added logic to the srp client example to demonstrate unregistering in response to receiving a UDP packet. 
- Bumps the version of esp-openthread to 0.4.0 (I should have done this in PR #15  but better late than never)
- Update as of 9/28: also bumps OT version to commit `6e46e2e9f172376cd72109d742961dbdc4b25ab5` and adds a method to register SRP client change callback

Its worth noting that its very easy to run into SRP service and host name collisions if you are running the srp example on multiple boards, and this is sort of a silent failure from the device's perspective currently. So I have also added a function to allow callers to generate a random `u32`, intended to allow them to randomize their hostname/service names if they want. Doing that at runtime requires using `alloc` for boxing & leaking modified strings as `'static`, so I did not go so far as to include that in the example. But happy to follow up with a new PR if that would be useful, or maybe there is another way to handle this that I am not thinking of that does not require pulling in `alloc`?

## Testing

Tested on both esp32c6 and esp32h2 boards with a raspberry pi BR providing SRP server; when boards successfully register and then unregister, SRP server logs will output logs such as:
```
otbr-agent[935]: [INFO]-ADPROXY-: Advertise SRP service updates: host=ot-esp32.default.service.arpa.
otbr-agent[935]: [INFO]-ADPROXY-: Handle publish SRP service 'ot-service._otpps._tcp.default.service.arpa.': OK
otbr-agent[935]: [INFO]-ADPROXY-: Handle publish SRP host 'ot-esp32.default.service.arpa.': OK
otbr-agent[935]: 2d.01:56:44.230 [I] SrpServer-----: Handler result of SRP update (id = 451897720) is received: OK
otbr-agent[935]: 2d.01:56:44.230 [I] SrpServer-----: Committing update for existing host ot-esp32.default.service.arpa.
otbr-agent[935]: 2d.01:56:44.230 [I] SrpServer-----:     Granted lease:7200, key-lease:680400, ttl:7200
otbr-agent[935]: 2d.01:56:44.230 [I] SrpServer-----: Update existing service 'ot-service._otpps._tcp.default.service.arpa.'
otbr-agent[935]: 2d.01:56:44.230 [I] SrpServer-----: Send success response with granted lease: 7200 and key lease: 680400
otbr-agent[935]: 2d.01:56:49.891 [I] SrpServer-----: Received DNS update from fd2e:c69b:fa93:1:4dad:9594:cd6b:cf87
otbr-agent[935]: 2d.01:56:49.901 [I] SrpServer-----: Processed SRP update info
otbr-agent[935]: 2d.01:56:49.901 [I] SrpServer-----:     Host:ot-esp32.default.service.arpa.
otbr-agent[935]: 2d.01:56:49.901 [I] SrpServer-----:     Lease:0, key-lease:0, ttl:7200
otbr-agent[935]: 2d.01:56:49.901 [I] SrpServer-----:     No host address
otbr-agent[935]: 2d.01:56:49.901 [I] SrpServer-----:     Deleting service 'ot-service._otpps._tcp.default.service.arpa.'
otbr-agent[935]: 2d.01:56:49.901 [I] SrpServer-----: SRP update handler is notified (updatedId = 451897721)
otbr-agent[935]: [INFO]-ADPROXY-: Advertise SRP service updates: host=ot-esp32.default.service.arpa.
otbr-agent[935]: [INFO]-ADPROXY-: Handle unpublish SRP service 'ot-service._otpps._tcp.default.service.arpa.': OK
otbr-agent[935]: [INFO]-ADPROXY-: Handle unpublish SRP host 'ot-esp32.default.service.arpa.': OK
otbr-agent[935]: 2d.01:56:49.902 [I] SrpServer-----: Handler result of SRP update (id = 451897721) is received: OK
otbr-agent[935]: 2d.01:56:49.902 [I] SrpServer-----: Committing update for existing host ot-esp32.default.service.arpa.
otbr-agent[935]: 2d.01:56:49.902 [I] SrpServer-----:     Granted lease:0, key-lease:0, ttl:30
otbr-agent[935]: 2d.01:56:49.902 [I] SrpServer-----: Fully remove host ot-esp32.default.service.arpa.
otbr-agent[935]: 2d.01:56:49.902 [I] SrpServer-----: Send success response
otbr-agent[935]: 2d.01:56:49.902 [I] SrpServer-----: Fully remove service 'ot-service._otpps._tcp.default.service.arpa.'
```

In the srp client example, the output should look like the following (and note that -any- udp packet it gets will trigger the unregister call, but the device should remain ping-able via link-local addr until if/when if drops off the network):
```
Initializing
dataset : OperationalDataset { active_timestamp: Some(ThreadTimestamp { seconds: 1, ticks: 0, authoritative: false }), pending_timestamp: None, network_key: Some([254, 4, 88, 247, 219, 150, 53, 78, 170, 96, 65, 184, 128, 234, 156, 15]), network_name: Some("OpenThread-58d1"), extended_pan_id: Some([58, 144, 227, 163, 25, 169, 4, 148]), mesh_local_prefix: None, delay: None, pan_id: Some(22737), channel: Some(25), pskc: None, security_policy: None, channel_mask: Some(134215680) }
Currently assigned addresses
fdde:ad00:beef:0:b9e0:8402:604d:1ffe
fe80::98a9:562:455:5cec

ChangedFlags(Ipv6AddressAdded | ThreadRoleChanged | ThreadLlAddressChanged | ThreadMeshLocalAddressChanged | ThreadKeySequenceChanged | ThreadNetworkDataChanged | Ipv6MulticastSubscribed | ThreadNetworkChannelChanged | ThreadPanIdChanged | ThreadNetworkNameChanged | ThreadExtendedPanIdChanged | ThreadNetworkKeyChanged | ThreadNetworkInterfaceStateChanged | ActiveDatasetChanged)
ChangedFlags(ThreadKeySequenceChanged)
ChangedFlags(ThreadRoleChanged | ThreadRlocAdded | ThreadPartitionIdChanged | ThreadNetworkDataChanged | PendingDatasetChanged)
Attached to network, can now register SRP service
Registered SRP service; hostname "ot-esp32\0", "ot-service", "_otpps._tcp"
ChangedFlags(Ipv6AddressAdded)
Currently assigned addresses
fd2e:c69b:fa93:1:97a6:d2b9:3444:1164
fdde:ad00:beef::ff:fe00:d914
fdde:ad00:beef:0:b9e0:8402:604d:1ffe
fe80::98a9:562:455:5cec

received [fa, ce, be, ef] from fd2e:c69b:fa93:1:134c:7a9f:bbe7:e5b5 port 0
Sent response message, now unregistering SRP service!
SRP services unregistered, no longer receiving UDP packets
```

### CODE REVIEW

**Review by bjoernQ — APPROVED** [review]
Thanks!

Pinning esp-hal version should be totally fine.

I guess if just the examples use alloc but the library doesn't depend on it that is not a problem at all (and if the library would need alloc for good reasons it wouldn't be too - but happy we don't)

**Comment by nand-nor** [comment]
OK I added `esp_alloc` & logic to randomize names in the SRP client example in commit 5fc9574. But while I was doing some stress testing I noticed that about once every 10-15 runs, the OT stack appears to lock up across different boards & different runs of the same binary. This is maybe due to a data race or some other type of race condition that the SRP code additions are causing to arise more frequently (or just entirely added, not sure yet).  

Im not 100% sure yet what the solution is, I tried to put a lock around the `otInstance` pointer thinking that the ISR-triggered callbacks were causing a datarace while OT stack was processing something with the mutable pointer, but that did not solve it completely just made it a bit less frequent. So depending on what you prefer, should maybe rollback to the previous commit (before SRP additions) until it can be fully resolved? Sorry I am late in catching this, I should have stress tested before the last PR. I will try to figure out a fix ASAP

**Comment by bjoernQ** [comment]
Thanks again for working on this.

Given the current experimental state of the crate and the fact you are actively working on hunting down the bug I think it's fine to wait for the fix.

**Comment by nand-nor** [comment]
Have just pushed two additional commits to fix the problem. While I was at it I bumped the OT version to the latest commit (`6e46e2e9f172376cd72109d742961dbdc4b25ab5`) as well. I also got rid of the unused libraries from the `build.rs` file in `esp-openthread-sys`. The OT bump/changes to `esp-openthread-sys` is all in commit https://github.com/esp-rs/esp-openthread/pull/16/commits/9ea964f4158b43efaf5f3809aaf909ec5fba7724. The fix for the OT stack lockup is in commit https://github.com/esp-rs/esp-openthread/pull/16/commits/f9679d1c57ba03aeedf603a3f9f83710e1eddca4. I will note that I dont think the bump in the OT commit is necessary for the fix so OK to drop or add that in a follow up PR if that is preferable. 

So far I have not been able to reproduce using the same methods that previously had been reliably reproducing. Should be good to merge if the changes are acceptable 🎉 🥳.

**Comment by bjoernQ** [comment]
I guess there is no problem in bumping the OT versions

> So far I have not been able to reproduce using the same methods that previously had been reliably reproducing. Should be good to merge if the changes are acceptable 🎉 🥳.

Awesome! Thank you!

This looks good to me - maybe let's see if @jessebraham wants to add something - if not this is fine to merge IMHO

**Comment by jessebraham** [comment]
Will do my best to take a look at this today or tommorow!

**Review by jessebraham — APPROVED** [review]
I have not had a chance to test this on hardware and have some other work to move on to, however I think the changes look completely reasonable, so let's go ahead and merge this. Thanks!

**Pull request merged**
